//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace Microsoft.Samples.Windows.Forms.Cs.Update.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UpdateCustomersSoap", Namespace="http://tempuri.org/")]
    public class UpdateCustomers : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UpdateCustomers() {
            this.Url = "http://localhost/quickstart/winforms/samples/data/Update/CS/UpdateCustomers.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Save(System.Data.DataSet customersDataSet) {
            object[] results = this.Invoke("Save", new object[] {
                        customersDataSet});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSave(System.Data.DataSet customersDataSet, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Save", new object[] {
                        customersDataSet}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndSave(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
