#
# Makefile
#

all: InboxViewer InboxViewer2

InboxViewer::
	cd $*
	- nmake all
	cd ..

InboxViewer2::
	cd $*
	- nmake all
	cd ..


clean: 
	-cd InboxViewer
	- nmake clean
	- cd ..

	-cd InboxViewer2
	- nmake clean
	- cd ..



