//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

import System.Diagnostics;
import System.Xml.Serialization;
import System;
import System.Web.Services.Protocols;
import System.ComponentModel;
import System.Web.Services;

//
//This source code was auto-generated by wsdl, Version=1.1.4322.573.
//
package SessionService1JS {
    
    ///<remarks/>
    public System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Web.Services.WebServiceBindingAttribute(Name="SessionService1Soap", Namespace="http://tempuri.org/") 
    class SessionService1 extends System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        ///<remarks/>
        public function SessionService1() {
            this.Url = "http://localhost/quickstart/aspplus/samples/services/Intrinsics/JS/SessionService" + 
"1.asmx";
            
        }
        
        ///<remarks/>
        public final System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateAppCounter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped) function UpdateAppCounter() : System.String {
            var results : System.Object[] = this.Invoke("UpdateAppCounter", new System.Object[0]);
            return System.String(results[0]);
        }
        
        ///<remarks/>
        public final function BeginUpdateAppCounter(callback : System.AsyncCallback, asyncState : System.Object) : System.IAsyncResult {
            return this.BeginInvoke("UpdateAppCounter", new System.Object[0], callback, asyncState);
        }
        
        ///<remarks/>
        public final function EndUpdateAppCounter(asyncResult : System.IAsyncResult) : System.String {
            var results : System.Object[] = this.EndInvoke(asyncResult);
            return System.String(results[0]);
        }
        
        ///<remarks/>
        public final System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateHitCounter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped) function UpdateHitCounter() : System.String {
            var results : System.Object[] = this.Invoke("UpdateHitCounter", new System.Object[0]);
            return System.String(results[0]);
        }
        
        ///<remarks/>
        public final function BeginUpdateHitCounter(callback : System.AsyncCallback, asyncState : System.Object) : System.IAsyncResult {
            return this.BeginInvoke("UpdateHitCounter", new System.Object[0], callback, asyncState);
        }
        
        ///<remarks/>
        public final function EndUpdateHitCounter(asyncResult : System.IAsyncResult) : System.String {
            var results : System.Object[] = this.EndInvoke(asyncResult);
            return System.String(results[0]);
        }
    }
}
