//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace SoapHeaders {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HeaderServiceSoap", Namespace="http://tempuri.org/")]
    public class HeaderService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public AuthHeaderCS AuthHeaderCSValue;
        
        /// <remarks/>
        public HeaderService() {
            this.Url = "http://localhost/quickstart/aspplus/samples/services/SoapHeaders/CS/SoapHeaders.a" +
"smx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderCSValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SecureMethod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SecureMethod() {
            object[] results = this.Invoke("SecureMethod", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSecureMethod(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SecureMethod", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSecureMethod(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public class AuthHeaderCS : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string Username;
        
        /// <remarks/>
        public string Password;
    }
}
