//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.573.
// 
namespace MatchService {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class TestIt : System.Web.Services.Protocols.HttpGetClientProtocol {
        
        /// <remarks/>
        public TestIt() {
            this.Url = "http://localhost";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.HttpMethodAttribute(typeof(System.Web.Services.Protocols.TextReturnReader), typeof(System.Web.Services.Protocols.UrlParameterWriter))]
        public TestHeadersMatches TestHeaders() {
            return ((TestHeadersMatches)(this.Invoke("TestHeaders", (this.Url + "/QuickStart/aspplus/samples/services/TextMatching/CS/MatchServer.html"), new object[0])));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTestHeaders(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TestHeaders", (this.Url + "/QuickStart/aspplus/samples/services/TextMatching/CS/MatchServer.html"), new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public TestHeadersMatches EndTestHeaders(System.IAsyncResult asyncResult) {
            return ((TestHeadersMatches)(this.EndInvoke(asyncResult)));
        }
    }
    
    public class TestHeadersMatches {
        
        [System.Web.Services.Protocols.MatchAttribute("TITLE>(.*?)<")]
        public string Title;
        
        [System.Web.Services.Protocols.MatchAttribute("H1>(.*?)<")]
        public string H1;
    }
}
