all:
	vbc ActiveDir.vb
	vbc Buffers.vb
	vbc CreateObject.vb
	vbc Errors.vb
	vbc FindFile.vb
	vbc /r:System.Windows.Forms.dll GCHandle.vb
	vbc HandleRef.vb
	vbc MsgBox.vb
	vbc OpenFileDlg.vb
	vbc OSInfo.vb
	vbc Printf.vb
	vbc SysTime.vb

clean:
	del *.exe


