//-----------------------------------------------------------------------
//  This file is part of the Microsoft .NET SDK Code Samples.
// 
//  Copyright (C) Microsoft Corporation.  All rights reserved.
// 
//This source code is intended only as a supplement to Microsoft
//Development Tools and/or on-line documentation.  See these other
//materials for detailed information regarding Microsoft code samples.
// 
//THIS CODE AND INFORMATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY
//KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
//IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
//PARTICULAR PURPOSE.
//-----------------------------------------------------------------------

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2914.16
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.0.2914.16.
// 
namespace XmlSerializationHowTo {
    using System.Xml.Serialization;
    
    
    [System.Xml.Serialization.XmlRootAttribute("purchaseOrder", Namespace="", IsNullable=false)]
    public class PurchaseOrder {
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public USAddress shipTo;
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public USAddress billTo;
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public string comment;
        
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public ItemsItem[] items;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime orderDate;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderDateSpecified;
    }
    
    public class USAddress {
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public string name;
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public string street;
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public string city;
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public string state;
        
        public System.Decimal zip;
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NMTOKEN")]
        public string country;
    }
    
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="")]
    public class ItemsItem {
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public string productName;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", IsNullable=false)]
        public string quantity;
        
        public System.Decimal USPrice;
        
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=false)]
        public string comment;
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=false)]
        public System.DateTime shipDate;
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shipDateSpecified;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string partNum;
    }
}
