'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=1.1.4322.573.
'

'<remarks/>
<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="DataServiceServiceSoap", [Namespace]:="http://tempuri.org/")>  _
Public Class DataServiceService
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    '<remarks/>
    Public Sub New()
        MyBase.New
        Me.Url = "http://localhost/quickstart/aspplus/samples/vstudio/services/DataService/VB/DataS"& _ 
"ervice.asmx"
    End Sub
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTitleAuthors", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function GetTitleAuthors() As System.Data.DataSet
        Dim results() As Object = Me.Invoke("GetTitleAuthors", New Object(-1) {})
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    Public Function BeginGetTitleAuthors(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("GetTitleAuthors", New Object(-1) {}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndGetTitleAuthors(ByVal asyncResult As System.IAsyncResult) As System.Data.DataSet
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),System.Data.DataSet)
    End Function
    
    '<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutTitleAuthors", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
    Public Function PutTitleAuthors(ByVal DS As System.Data.DataSet) As Integer
        Dim results() As Object = Me.Invoke("PutTitleAuthors", New Object() {DS})
        Return CType(results(0),Integer)
    End Function
    
    '<remarks/>
    Public Function BeginPutTitleAuthors(ByVal DS As System.Data.DataSet, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("PutTitleAuthors", New Object() {DS}, callback, asyncState)
    End Function
    
    '<remarks/>
    Public Function EndPutTitleAuthors(ByVal asyncResult As System.IAsyncResult) As Integer
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),Integer)
    End Function
End Class
