all:
	csc ActiveDir.cs
	csc Buffers.cs
	csc CreateObject.cs
	csc Errors.cs
	csc FindFile.cs
	csc GCHandle.cs
	csc HandleRef.cs
	csc MsgBox.cs
	csc OpenFileDlg.cs
	csc OSInfo.cs
	csc Printf.cs
	csc SysTime.cs

clean:
	del *.exe


