#
# Interop Samples Makefile
#

all: Advanced Applications Basic PlatformInvoke

Advanced::
	cd $*
	- nmake all
	cd ..

Applications::
	cd $*
	- nmake all
	cd ..

Basic::
	cd $*
	- nmake all
	cd ..
	
PlatformInvoke::
	cd $*
	- nmake all
	cd ..	

clean:
	cd Advanced
	- nmake clean
	cd ..

	cd Applications
	- nmake clean
	cd ..

	cd Basic
	- nmake clean
	cd ..

	cd PlatformInvoke
	- nmake clean
	cd ..