'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=1.1.4322.573.
'
Namespace MatchServiceVB
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Public Class TestIt
        Inherits System.Web.Services.Protocols.HttpGetClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.HttpMethodAttribute(GetType(System.Web.Services.Protocols.TextReturnReader), GetType(System.Web.Services.Protocols.UrlParameterWriter))>  _
        Public Function TestHeaders() As TestHeadersMatches
            Return CType(Me.Invoke("TestHeaders", (Me.Url + "/QuickStart/aspplus/samples/services/TextMatching/VB/MatchServer.html"), New Object(-1) {}),TestHeadersMatches)
        End Function
        
        '<remarks/>
        Public Function BeginTestHeaders(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TestHeaders", (Me.Url + "/QuickStart/aspplus/samples/services/TextMatching/VB/MatchServer.html"), New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTestHeaders(ByVal asyncResult As System.IAsyncResult) As TestHeadersMatches
            Return CType(Me.EndInvoke(asyncResult),TestHeadersMatches)
        End Function
    End Class
    
    Public Class TestHeadersMatches
        
        <System.Web.Services.Protocols.MatchAttribute("TITLE>(.*?)<")>  _
        Public Title As String
        
        <System.Web.Services.Protocols.MatchAttribute("H1>(.*?)<")>  _
        Public H1 As String
    End Class
End Namespace
