all: RemotingHello RemotingObjects RemotingCollections RemotingEvents

RemotingHello::
	cd $*
	nmake -a all
	cd ..

RemotingObjects::
	cd $*
	nmake -a all
	cd ..

RemotingCollections::
	cd $*
	nmake -a all
	cd ..

RemotingEvents::
	cd $*
	nmake -a all
	cd ..
