all: ConsoleClient ConsoleClientAll ConsoleClientDirect RemotingHelloWebClient

ConsoleClient:
	cd $*
	nmake -a all
	cd ..

ConsoleClientAll:
	cd $*
	nmake -a all
	cd ..

ConsoleClientDirect:
	cd $*
	nmake -a all
	cd ..

RemotingHelloWebClient:
	cd $*
	nmake -a all
	cd ..

