<%@ Register TagPrefix="Acme" TagName="TocSwitch" Src="../util/TocSwitch.ascx"%>
<!--BEGIN HEADER-->
<html>

<head>
<link rel="stylesheet" href="/MobileQuickstart/include/qsstyle.css">
<title>.NET Mobile Web SDK QuickStart Tutorial</title>
</head>

<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0">

<table class="outer" cellpadding="0" cellspacing="0" height="100%">
<tr>

<Acme:TocSwitch runat="server" />

<td valign="top" width="100%">
<div class="body">
<!--END HEADER-->
