<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo's QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td class="toc" valign="top" width="210">






<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">

		<div style="padding:0,0,4,0"><b>Collections</b><br></div>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/List.aspx">Iterate over a collection</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Hashtable.aspx">Use a Hashtable collection</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Queue.aspx">Choose a collection to use</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/icollection.aspx">Implement a collection</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/clone.aspx">Clone a collection</a><p>

		<div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>


                             <p>
		 <Acme:UrlMaker runat="server" />

</div>

</td>
</tr>
</table>






</td>
 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->

<!-- #include virtual="/quickstart/howto/doc/xml/xmldataheader.inc" -->

