<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo's QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td class="toc" valign="top" width="210">

<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">

    <div style="padding:0,0,4,0"><b>Data and ADO.NET</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/ADOPlusOverview.aspx">Overview of ADO.NET</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/ExecuteCommand.aspx">Execute a Command</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/OutParams.aspx">Get Out Parameters from a Stored Procedure</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/GetDataFromDB.aspx">Populate a DataSet from a Database</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/UpdateDataFromDB.aspx">Update a Database from a DataSet</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/ReadandWriteXml.aspx">Read and Write XML</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/DatabaseTrans.aspx">Use Database Transactions</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/HandleErrors.aspx">Handle Errors</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/RelationalData.aspx">Work with Relational Data</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/TypedData.aspx">Work with Typed Data</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/FilterData.aspx">Filter Data</a><br>

    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/connectionpooling.aspx">Use Connection Pooling</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/xmlfromsqlsrv.aspx">Generate XML with data from SQL Server</a><br>
    <!-- &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/updategram.aspx">Use UpdateGram with SQL Server</a><br> -->
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/adorstodataset.aspx">Load a native ADO recordset into a DataSet</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/adodtreader.aspx">Retrieve Data Using OLE DB</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/sqldtreader.aspx">Retrieve Data from SQL Server</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/employees.aspx">Convert an ADO Application to ADO.NET</a><p>
    <div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>

		<p>
		<Acme:UrlMaker runat="server" />

</div>

</td>
</tr>
</table>

</td>
 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->

<!-- #include virtual="/quickstart/howto/doc/xml/xmldataheader.inc" -->

