<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo's QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td class="toc" valign="top" width="210">

<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">

    <div style="padding:0,0,4,0"><b>Diagnostics</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/LogWrite.aspx">Write to an event log</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/LogInfo.aspx">Read from an event log</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/LogMonitor.aspx">Monitor an event log</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/PCWrite.aspx">Write to a performance counter</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/PCRead.aspx">Read from a performance counter</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/PCDemo.aspx">Count rate of change</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Trace.aspx">Work with tracing</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Switches.aspx">Use trace switches and listeners</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/TraceDemo.aspx">Instrument an application</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/ProcessDemo.aspx">Start and stop a process</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/PrInfo.aspx">Get process information</a><p>
    <div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>

		<p>
		<Acme:UrlMaker runat="server" />

</div>

</td>
</tr>
</table>

</td>
 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->

<!-- #include virtual="/quickstart/howto/doc/xml/xmldataheader.inc" -->

