<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo's QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td class="toc" valign="top" width="210">

<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">


    		<div style="padding:0,0,4,0"><b>Introduction</b><br></div>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/Interop_Overview.aspx">Interop Overview</a><p>

    		<div style="padding:0,0,4,0"><b>Using .NET from COM</b><br></div>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/Building_Samples_COM2NET.aspx">Build a .NET COM Server</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/TestServer_1.aspx">Pass simple data to VB6</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/TestServer_2.aspx">Pass an array to VB6</a><p>

		<div style="padding:0,0,4,0"><b>Using COM from .NET</b><br></div>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/Building_Samples_NET2COM.aspx">Build a .NET COM Client</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/TestClient_1.aspx">Call COM methods</a><br>

		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/TestClient_2.aspx">Sink unmanaged events</a><br>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/StringMarshal.aspx">Marshal strings</a><p>

		<div style="padding:0,0,4,0"><b>Platform Invoke</b><br></div>
		&nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/PInvoke_Simple.aspx">Call a DLL Export</a><p>


		<div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>

    <p>
     <Acme:UrlMaker runat="server" />


</div>

</td>
</tr>
</table>

 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->
