<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo's QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td class="toc" valign="top" width="210">

<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">

    <div style="padding:0,0,4,0"><b>Languages</b><br></div>

    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#VariableDeclaration">Declare a variable</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Statements">Issue a statement</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Comments">Comment my code</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#SimpleProperty">Declare a simple property</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#UseIndexedProperty">Use an indexed property</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#DeclareIndexedProperty">Declare an indexed property</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Enumeration">Declare an enumeration</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#EnumerateCollection">Enumerate a collection or array</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Methods">Declare and use a method</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#CustomAttr">Define custom attributes</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Arrays">Declare and use an array</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Initialization">Statically initialize a variable</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#IFState">Write an if statement</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#CaseState">Write a case statement</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#ForLoop">Write a for loop</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#WhileLoop">Write a while loop</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Exceptions">Handle exceptions</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#StringCat">Concatenate a string</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#DeclareEvent">Declare an event</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#DeclareHandler">Declare an event handler</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#AddRemoveHandler">Add an event handler</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Casting">Cast a variable to a type</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Convert">Convert a variable to type</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#ClassDef">Declare a class or interface</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#ClassDef">Inherit from a base class</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#InterfaceImpl">Implement an interface</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#ClassMain">Class with a main method</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Languages.aspx#Module">Write a standard module</a><br>

    <p>

    <div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>

    <p>
     <Acme:UrlMaker runat="server" />

</div>

</td>
</tr>
</table>






</td>
 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->

<!-- #include virtual="/quickstart/howto/doc/xml/xmldataheader.inc" -->

