<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td class="toc" valign="top" width="210">

<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">

    <div style="padding:0,0,4,0"><b>Networking</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientGET.aspx">Make a GET request</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientGETwithSSL.aspx">Make an SSL GET request</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientGETwithNTLM.aspx">Make an NTLM GET request</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientGETwithProxy.aspx">Make a proxy GET request</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientGETAsync.aspx">Make an async GET request</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/ASPXNet/GET.aspx">Make a GET request in ASP.NET</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/ASPXNet/GETAsync.aspx">Async GET request in ASP.NET</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientException.aspx">Handle WebExceptions</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientPOST.aspx">Make a POST request</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/TCPUDP/DateTimeClient.aspx">Write a TCPClient client</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/TCPUDP/DateTimeServer.aspx">Write a TCPListener server</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/TCPUDP/BroadcastChatClient.aspx">Write a UDPClient client</a><p>
    <div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>

    <p>
     <Acme:UrlMaker runat="server" />


</div>

</td>
</tr>
</table>






</td>
 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->

<!-- #include virtual="/quickstart/howto/doc/xml/xmldataheader.inc" -->

