<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td class="toc" valign="top" width="210">

<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">

    <div style="padding:0,0,4,0"><b>Remoting</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/mainfeatures.aspx">Remoting Overview</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/nutshell.aspx">How Remoting Works</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/quickstart.aspx">Remoting Samples</a><p>
    <div style="padding:0,0,4,0"><b>The Basics</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/firstserver.aspx">Create a Remote Server</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/firstclient.aspx">Create a Client of the Server</a><p>
    <div style="padding:0,0,4,0"><b>Samples</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/singleton.aspx">Create a Singleton Object</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/byreference.aspx">Pass Objects By Reference</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/byvalue.aspx">Pass Objects By Value</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/interface.aspx">Compile Against an Interface</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/Remoting/async.aspx">Make an Asynchronous Call</a><p>
    <div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>

    <p>
     <Acme:UrlMaker runat="server" />


</div>

</td>
</tr>
</table>






</td>
 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->

<!-- #include virtual="/quickstart/howto/doc/xml/xmldataheader.inc" -->

