<%@ Register TagPrefix="AcmeInclude" Namespace="Acme" Assembly="TocSwitch" %>
<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<!--BEGIN HEADER-->
<html>
<head>
 <title>Microsoft HowTo QuickStarts Tutorial</title>
<link rel="stylesheet" href="/quickstart/include/qsstyle.css">
</head>
<body topmargin="0" leftmargin="0" marginwidth="0" marginheight="0" >

<table class="outer" cellpadding=0 cellspacing=0>
<tr>
<td class="toc" valign="top" width="210">

<table>
<tr>
<AcmeInclude:TocSwitch runat="server"><TocTemplate>
<td nowrap style="padding-right:15">

<div class="toc" style="color:darkred;">

    <div style="padding:0,0,4,0"><b>Microsoft .NET Framework</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/security/CodeIdentityDemand.aspx">Control access to a component?</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/security/WindowsIdentityCheck.aspx">Check Windows Identity?</a><br>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/security/RequestPermissions.aspx">Request permissions?</a><p>

    <div style="padding:0,0,4,0"><b>Administration</b><br></div>
    &nbsp; <a class="outer" href="/quickstart/howto/doc/security/SecScripting.aspx">Script security policy changes?</a><p>


    <div style="padding:0,0,4,0"><b>ASP.NET Security</b><br></div>
    &nbsp; <a class="outer" target="_top" href="/quickstart/aspplus/default.aspx?url=/quickstart/aspplus/doc/securityoverview.aspx">Secure an ASP.NET application?</a><br>
    &nbsp; <a class="outer" target="_top" href="/quickstart/aspplus/default.aspx?url=/quickstart/aspplus/doc/windowsauth.aspx">Check Windows Identity?</a><br>
    &nbsp; <a class="outer" target="_top" href="/quickstart/aspplus/default.aspx?url=/quickstart/aspplus/doc/formsauth.aspx">Apply forms-based authentication?</a><br>
    &nbsp; <a class="outer" target="_top" href="/quickstart/aspplus/default.aspx?url=/quickstart/aspplus/doc/authorization.aspx">Authorize users or roles?</a><p>

    <div style="padding:0,0,4,0"><a target="_top" style="color:darkred" href="/quickstart/howto"><b>Back to Index</b></a><br></div>

    <p>
     <Acme:UrlMaker runat="server" />

</div>

</td>
</tr>
</table>

</td>
 </TocTemplate></AcmeInclude:TocSwitch>
<td valign="top">
<div class="body">
<!--END HEADER-->

<!-- #include virtual="/quickstart/howto/doc/xml/xmldataheader.inc" -->

