<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/howto/util/UrlMaker.ascx"%>
<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="font-size:x-small;color:darkred;">

            <div style="padding:0,0,4,8"><b>A</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/ADRead.aspx">Active Directory</a><br>
            &nbsp; <a class="outer" href="/quickstart/aspplus/" target="_top">ASP.NET</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/sharedname.aspx">Assemblies</a><p>
            <div style="padding:0,0,4,8"><b>B</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/sort.aspx">Base Data Types</a><p>
            <div style="padding:0,0,4,8"><b>C</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/list.aspx">Collections</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/listbuilder.aspx">Component Model</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/configclient.aspx">Configuration</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/fileencrypt.aspx">Cryptography</a><p>
            <div style="padding:0,0,4,8"><b>D</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/adoplus/adoplusoverview.aspx">Data and ADO.NET</a><br>
            &nbsp; <a class="outer" target="_top" href="/quickstart/aspplus/default.aspx?url=/quickstart/aspplus/doc/debugcomsdk.aspx">Debugging</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/logwrite.aspx">Diagnostics</a><p>
            <div style="padding:0,0,4,8"><b>E</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/catch.aspx">Exceptions</a><p>
            <div style="padding:0,0,4,8"><b>F</b><br></div>
            <div style="padding:0,0,4,8"><b>G</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/encoding.aspx">Globalization and NLS</a><p>
            <div style="padding:0,0,4,8"><b>H</b><br></div>
            <div style="padding:0,0,4,8"><b>I</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/anagrams.aspx">Input and Output</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/Interop/Interop_Overview.aspx">Interoperability</a><p>
            <div style="padding:0,0,4,8"><b>J</b><br></div>
            <div style="padding:0,0,4,8"><b>K</b><br></div>
            <div style="padding:0,0,4,8"><b>L</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/languages.aspx">Languages</a><p>
            <div style="padding:0,0,4,8"><b>M</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/mqsend.aspx">Messaging</a><p>
            &nbsp; <a class="outer" href="/MobileQuickstart/" target="_top">Mobile Web Development</a><br>
            <div style="padding:0,0,4,8"><b>N</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/WebRequests/clientGET.aspx">Networking</a><p>
            <div style="padding:0,0,4,8"><b>O</b><br></div>
            <div style="padding:0,0,4,8"><b>P</b><br></div>
            <div style="padding:0,0,4,8"><b>Q</b><br></div>
            <div style="padding:0,0,4,8"><b>R</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/GetTypes.aspx">Reflection</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/regexmatch.aspx">Regular Expressions</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/remoting/mainfeatures.aspx">Remoting</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/CreateResources.aspx">Resources</a><p>
            <div style="padding:0,0,4,8"><b>S</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/security/CodeIdentityDemand.aspx">Security</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/serialize.aspx">Serialization</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/simpleservice.aspx">Services</a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/installers.aspx">Setup</a><p>
            <div style="padding:0,0,4,8"><b>T</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/timer.aspx">Timers</a><p>
            <div style="padding:0,0,4,8"><b>U</b><br></div>
            <div style="padding:0,0,4,8"><b>V</b><br></div>
            <div style="padding:0,0,4,8"><b>W</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/WinForms/WinFormsAppErrorHandler.aspx">Windows Forms</a><p>
            <div style="padding:0,0,4,8"><b>X</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/xml/overviewofxml.aspx">XML Data </a><br>
            &nbsp; <a class="outer" href="/quickstart/howto/doc/xmlserialization/XSDFromCls.aspx">XML Serialization</a><br>
	    &nbsp; <a class="outer" href="/quickstart/aspplus/doc/writingservices.aspx">XML Web services</a><p>
            <div style="padding:0,0,4,8"><b>Y</b><br></div>
            <div style="padding:0,0,4,8"><b>Z</b><br></div>

            <p>

            <Acme:UrlMaker runat="server" />

</div>

</td>
</tr>
</table>
