<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/aspplus/util/UrlMaker.ascx"%>
<table>
  <tr>
    <td nowrap style="padding-right:15">
      <div class="toc" style="font-size:x-small;color:darkred;">

        <div style="padding:0,0,4,0"><b>Getting Started</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/quickstart.aspx">Introduction</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/whatisaspx.aspx">What is ASP.NET?</a><br>
        &nbsp; <a class="outer" target="_top" href="/QuickStart/howto/default.aspx?url=/quickstart/howto/doc/languages.aspx">Language Support</a><br><p>

        <div style="padding:0,0,4,0"><b>ASP.NET Web Forms</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webformsintro.aspx">Introducing Web Forms</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webserverctrls.aspx">Working with Server Controls</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webtemplates.aspx">Applying Styles to Controls</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webvalidation.aspx">Server Control Form Validation</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webpagelets.aspx">Web Forms User Controls</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webdatabinding.aspx">Data Binding Server Controls</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webdataaccess.aspx">Server-Side Data Access</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webdatalist.aspx">Data Access and Customization</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/businessobjs.aspx">Working with Business Objects</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webctrlauthoring.aspx">Authoring Custom Controls</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webcontrolsref.aspx">Web Forms Controls Reference</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webformssyntaxref.aspx">Web Forms Syntax Reference</a><p>

        <div style="padding:0,0,4,0"><b>XML Web services<br>&nbsp;&nbsp;&nbsp;created using ASP.NET</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webservicesintro.aspx">Introducing XML Web services</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/writingservices.aspx">Writing a Simple XML Web service</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/webservicetypes.aspx">XML Web service Type Marshalling</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/servicesanddata.aspx">Using Data in XML Web services</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/servicesandobjs.aspx">Using Objects and Intrinsics</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/wsbehavior.aspx">The XML Web service Behavior</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/htmlscraping.aspx">HTML Pattern Matching</a><p>

        <div style="padding:0,0,4,0"><b>ASP.NET Web Applications</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/applications.aspx">Application Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/globalasax.aspx">Using the Global.asax File</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/stateoverview.aspx">Managing Application State</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/httphandlers.aspx">HttpHandlers and Factories</a><p>

        <div style="padding:0,0,4,0"><b>Cache Services</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/cachingoverview.aspx">Caching Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/outputcaching.aspx">Page Output Caching</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/fragmentcaching.aspx">Page Fragment Caching</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/datacaching.aspx">Page Data Caching</a><p>

        <div style="padding:0,0,4,0"><b>Configuration</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/configoverview.aspx">Configuration Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/configformat.aspx">Configuration File Format</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/configretrieve.aspx">Retrieving Configuration</a><p>

        <div style="padding:0,0,4,0"><b>Deployment</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/deployment.aspx">Deploying Applications</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/procmodel.aspx">Using the Process Model</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/handlingerrs.aspx">Handling Errors</a><p>

        <div style="padding:0,0,4,0"><b>Security</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/securityoverview.aspx">Security Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/authandauth.aspx">Authentication & Authorization</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/windowsauth.aspx">Windows-based Authentication</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/formsauth.aspx">Forms-based Authentication</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/authorization.aspx">Authorizing Users and Roles</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/impersonation.aspx">User Account Impersonation</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/secureservices.aspx">Security and WebServices</a><p>

        <div style="padding:0,0,4,0"><b>Localization</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/internationalization.aspx">Internationalization Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/cultureencoding.aspx">Setting Culture and Encoding</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/localizingapps.aspx">Localizing ASP.NET Applications</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/resourcefiles.aspx">Working with Resource Files</a><p>

        <div style="padding:0,0,4,0"><b>Tracing</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/tracingoverview.aspx">Tracing Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/tracelogpage.aspx">Trace Logging to Page Output</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/tracelogapp.aspx">Application-level Trace Logging</a><p>

        <div style="padding:0,0,4,0"><b>Debugging</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/debugcomsdk.aspx">The SDK Debugger</a><p>

        <div style="padding:0,0,4,0"><b>Performance</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/perfoverview.aspx">Performance Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/perftuning.aspx">Performance Tuning Tips</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/perfmeasure.aspx">Measuring Performance</a><p>

        <div style="padding:0,0,4,0"><b>ASP to ASP.NET Migration</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/migrationoverview.aspx">Migration Overview</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/syntaxandsemantics.aspx">Syntax and Semantics</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/languagecompat.aspx">Language Compatibility</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/cominterop.aspx">COM Interoperability</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/mtstransactions.aspx">MTS Transactions</a><p>

        <div style="padding:0,0,4,0"><b>Sample Applications</b><br></div>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/portalapp.aspx">A Personalized Portal</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/ecommerceapp.aspx">An E-Commerce Storefront</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/classbrowser.aspx">A Class Browser Application</a><br>
        &nbsp; <a class="outer" href="/quickstart/aspplus/doc/ibuyspy.aspx">IBuySpy.com</a><p>
      </div>
      <p>

        &nbsp; <Acme:UrlMaker runat="server" /><p>

    </td>
  </tr>
</table>