
  <table width=100% cellspacing=0 cellpadding=0>
    <tr>
      <td style="height:20" bgcolor="#9C0001" cellspacing=0 cellpadding=0 width=100%/>
    </tr>
    <tr>
      <td align="right" style="height:70;font-family:Arial;font-weight:bold;font-size:44pt;color:white" width="100%" bgcolor="D3C9C7">
              <font size=6 color="#FFFFFF">The Book Cellar&nbsp;</font>
      </td>
    </tr>
  </table>
