//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

import System.Diagnostics;
import System.Xml.Serialization;
import System;
import System.Web.Services.Protocols;
import System.ComponentModel;
import System.Web.Services;

//
//This source code was auto-generated by wsdl, Version=1.1.4322.573.
//
package DataServiceJS {
    
    ///<remarks/>
    public System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Web.Services.WebServiceBindingAttribute(Name="DataServiceSoap", Namespace="http://tempuri.org/") 
    class DataService extends System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        ///<remarks/>
        public function DataService() {
            this.Url = "http://localhost/quickstart/aspplus/samples/services/dataservice/JS/dataservice.a" + 
"smx";
            
        }
        
        ///<remarks/>
        public final System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutTitleAuthors", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped) function PutTitleAuthors(ds : System.Data.DataSet) : int {
            var results : System.Object[] = this.Invoke("PutTitleAuthors", [ds]);
            return int(results[0]);
        }
        
        ///<remarks/>
        public final function BeginPutTitleAuthors(ds : System.Data.DataSet, callback : System.AsyncCallback, asyncState : System.Object) : System.IAsyncResult {
            return this.BeginInvoke("PutTitleAuthors", [ds], callback, asyncState);
        }
        
        ///<remarks/>
        public final function EndPutTitleAuthors(asyncResult : System.IAsyncResult) : int {
            var results : System.Object[] = this.EndInvoke(asyncResult);
            return int(results[0]);
        }
        
        ///<remarks/>
        public final System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTitleAuthors", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped) function GetTitleAuthors() : System.Data.DataSet {
            var results : System.Object[] = this.Invoke("GetTitleAuthors", new System.Object[0]);
            return System.Data.DataSet(results[0]);
        }
        
        ///<remarks/>
        public final function BeginGetTitleAuthors(callback : System.AsyncCallback, asyncState : System.Object) : System.IAsyncResult {
            return this.BeginInvoke("GetTitleAuthors", new System.Object[0], callback, asyncState);
        }
        
        ///<remarks/>
        public final function EndGetTitleAuthors(asyncResult : System.IAsyncResult) : System.Data.DataSet {
            var results : System.Object[] = this.EndInvoke(asyncResult);
            return System.Data.DataSet(results[0]);
        }
    }
}
