<%@ Register TagPrefix="Acme" TagName="UrlMaker" Src="/quickstart/winforms/util/UrlMaker.ascx"%>
<table>
<tr>
<td nowrap style="padding-right:15">

<div class="toc" style="font-size:x-small;color:darkred;">

            <div style="padding:0,0,0,0"><a class=outer style="color:darkred" href="/quickstart/winforms/doc/default.aspx"><b>Introduction</b></a><br></div>
            <p>
            <div style="padding:0,0,4,0"><b>Getting Started</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsGettingStarted.aspx">What is Windows Forms?</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsSimpleHelloWorld.aspx">Writing a Hello World Form</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsApplicationModel.aspx">Windows Forms Application Model</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsFormLayout.aspx">Dynamic Layout in Windows Forms</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsMenus.aspx">Adding Menus to a Form</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsMDI.aspx">Writing MDI Applications</a><p>

            <div style="padding:0,0,4,0"><b>Building Applications</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/DataAccessPlaceHolder.aspx">Data Access Overview</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WebServicesPlaceHolder.aspx">XML Web services Overview</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsData.aspx">Databinding in Windows Forms</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsAxHosting.aspx">Using ActiveX Controls</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsIeSourcing.aspx">Controls in Internet Explorer</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsGDIPlus.aspx">Working with Graphics</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsPrinting.aspx">Working with Printing</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsCreatingControls.aspx">Creating Controls</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsMSAA.aspx">Accessibility</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsLocalization.aspx">Localization</a><p>

            <div style="padding:0,0,4,0"><b>Control Reference</b><br></div>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ButtonCtl.aspx">Button</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/CheckBoxCtl.aspx">CheckBox</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/CheckedListBoxCtl.aspx">CheckedListBox</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ColorDialogCtl.aspx">ColorDialog</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ComboBoxCtl.aspx">ComboBox</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ContextMenuCtl.aspx">ContextMenu</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/DataGridCtl.aspx">DataGrid</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/DateTimePickerCtl.aspx">DateTimePicker</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/UpDownCtl.aspx">DomainUpDown</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ErrorProviderCtl.aspx">ErrorProvider</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/FontDialogCtl.aspx">FontDialog</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/GroupBoxCtl.aspx">GroupBox</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ScrollBarCtl.aspx">HScrollBar</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ImageListCtl.aspx">ImageList</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/LabelCtl.aspx">Label</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/LinkLabelCtl.aspx">LinkLabel</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ListBoxCtl.aspx">ListBox</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ListViewCtl.aspx">ListView</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/MainMenuCtl.aspx">MainMenu</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/UpDownCtl.aspx">NumericUpDown</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/OpenFileDialogCtl.aspx">OpenFileDialog</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/PageSetupDialogCtl.aspx">PageSetupDialog</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/PanelCtl.aspx">Panel</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/PictureBoxCtl.aspx">PictureBox</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/PrintDialogCtl.aspx">PrintDialog</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsPrinting.aspx#Example5">PrintDocument</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/WinFormsPrinting.aspx#Example5">PrintPreviewControl</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/PrintPreviewDialogCtl.aspx">PrintPreviewDialog</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ProgressBarCtl.aspx">ProgressBar</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/PropertyGridCtl.aspx">PropertyGrid</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/RadioButtonCtl.aspx">RadioButton</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/RichTextBoxCtl.aspx">RichTextBox</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/SaveFileDialogCtl.aspx">SaveFileDialog</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/StatusBarCtl.aspx">StatusBar</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/TabControlCtl.aspx">TabControl</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/TextBoxCtl.aspx">TextBox</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/TimerCtl.aspx">Timer</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ToolBarCtl.aspx">ToolBar</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ToolTipCtl.aspx">ToolTip</a><br>

            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/TrackBarCtl.aspx">TrackBar</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/TreeViewCtl.aspx">TreeView</a><br>
            &nbsp; <a class="outer" href="/quickstart/winforms/doc/ControlRef/ScrollBarCtl.aspx">VScrollBar</a><br>

            <p>

      <Acme:UrlMaker runat="server" />

</div>

</td>
</tr>
</table>

