all: ActiveDS ASPXTOADO DirectX InternetExplorer ManagedEvents WinForms

ActiveDS::
	cd $*
	- nmake all
	cd ..

ASPXTOADO::
	cd $*
	- nmake all
	cd ..

DirectX::
	cd $*
	- nmake all
	cd ..

InternetExplorer::
	cd $*
	- nmake all
	cd ..

ManagedEvents::
	cd $*
	- nmake all
	cd ..

WinForms::
	cd $*
	- nmake all
	cd ..

clean:
	cd ActiveDS
	- nmake clean
	cd ..

	cd ASPXTOADO
	- nmake clean
	cd ..

	cd DirectX
	- nmake clean
	cd ..

	cd InternetExplorer
	- nmake clean
	cd ..

	cd ManagedEvents
	- nmake clean
	cd ..

	cd WinForms
	- nmake clean
	cd ..
