all: Bank CDO ComServices LoanApps MPView ShellCmd WMI

Bank::
	cd $*
	- nmake all
	cd ..

CDO::
	cd $*
	- nmake all
	cd ..


ComServices::
	cd $*
	- nmake all
	cd ..

LoanApps::
	cd $*
	- nmake all
	cd ..

MPView::
	cd $*
	- nmake all
	cd ..

ShellCmd::
	cd $*
	- nmake all
	cd ..

WMI::
	cd $*
	- nmake all
	cd ..


clean:
	cd Bank
	- nmake clean
	cd ..

	cd CDO
	- nmake clean
	cd ..

	cd ComServices
	- nmake clean
	cd ..

	cd LoanApps
	- nmake clean
	cd ..

	cd MPView
	- nmake clean
	cd ..

	cd ShellCmd
	- nmake clean
	cd ..

	cd WMI
	- nmake clean
	cd ..


