cd %NETSAMPLEPATH%\QuickStart\howto\samples\assemblies\version\CS\calcrv5
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\assemblies\version\CP\calcrv5
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\assemblies\version\CS\calcrv6
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\assemblies\version\CP\calcrv6
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\Interop\TestServer_1\CS
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\Interop\TestServer_1\VB
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\Interop\TestServer_1\CP
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\Interop\TestServer_2\CS
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\Interop\TestServer_2\VB
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\Interop\TestServer_2\CP
nmake all
cd %NETSAMPLEPATH%\QuickStart\howto\samples\Interop\StringMarshal
nmake all
cd %NETSAMPLEPATH%\QuickStart\winforms\samples\AxHosting
nmake all