all: AsyncDelegate CallContext ChannelSinks CustomProxies RemotingCOM Serialization

AsyncDelegate::
	cd $*
	nmake -a all
	cd ..

CallContext::
	cd $*
	nmake -a all
	cd ..

ChannelSinks::
	cd $*
	nmake -a all
	cd ..

CustomProxies::
	cd $*
	nmake -a all
	cd ..

RemotingCOM::
	cd $*
	nmake -a all
	cd ..

Serialization::
	cd $*
	nmake -a all
	cd ..
