//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 1.1.4322.573
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

import System.Diagnostics;
import System.Xml.Serialization;
import System;
import System.Web.Services.Protocols;
import System.ComponentModel;
import System.Web.Services;

//
//This source code was auto-generated by wsdl, Version=1.1.4322.573.
//
package SoapHeadersJS {
    
    ///<remarks/>
    public System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Web.Services.WebServiceBindingAttribute(Name="HeaderServiceSoap", Namespace="http://tempuri.org/") 
    class HeaderService extends System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public var sHeader : AuthHeader;
        
        ///<remarks/>
        public function HeaderService() {
            this.Url = "http://localhost/quickstart/aspplus/samples/services/SoapHeaders/JS/SoapHeaders.a" + 
"smx";
            
        }
        
        ///<remarks/>
        public final System.Web.Services.Protocols.SoapHeaderAttribute("sHeader") System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SecureMethod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped) function SecureMethod() : System.String {
            var results : System.Object[] = this.Invoke("SecureMethod", new System.Object[0]);
            return System.String(results[0]);
        }
        
        ///<remarks/>
        public final function BeginSecureMethod(callback : System.AsyncCallback, asyncState : System.Object) : System.IAsyncResult {
            return this.BeginInvoke("SecureMethod", new System.Object[0], callback, asyncState);
        }
        
        ///<remarks/>
        public final function EndSecureMethod(asyncResult : System.IAsyncResult) : System.String {
            var results : System.Object[] = this.EndInvoke(asyncResult);
            return System.String(results[0]);
        }
    }
    
    ///<remarks/>
    public System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/") System.Xml.Serialization.XmlRootAttribute("sHeader", Namespace="http://tempuri.org/", IsNullable=false) 
    class AuthHeader extends System.Web.Services.Protocols.SoapHeader {
        
        ///<remarks/>
        public var Username : System.String;
        
        ///<remarks/>
        public var Password : System.String;
    }
}
