all: BinaryFormatter SoapFormatter SoapMessage ISerializable

BinaryFormatter::
  cd $*
  nmake -a all
  cd ..

SoapFormatter::
  cd $*
  nmake -a all
  cd ..

SoapMessage::
  cd $*
  nmake -a all
  cd ..

ISerializable::
  cd $*
  nmake -a all
  cd ..